// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_INFOCHANNEL_PROTOCOLS_H_
#define FLATBUFFERS_GENERATED_INFOCHANNEL_PROTOCOLS_H_

#include "flatbuffers/flatbuffers.h"

namespace Protocols {

struct InfoChannel;

struct InfoChannel FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4
  };
  uint64_t id() const { return GetField<uint64_t>(VT_ID, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID) &&
           verifier.EndTable();
  }
};

struct InfoChannelBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) { fbb_.AddElement<uint64_t>(InfoChannel::VT_ID, id, 0); }
  InfoChannelBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  InfoChannelBuilder &operator=(const InfoChannelBuilder &);
  flatbuffers::Offset<InfoChannel> Finish() {
    auto o = flatbuffers::Offset<InfoChannel>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<InfoChannel> CreateInfoChannel(flatbuffers::FlatBufferBuilder &_fbb,
   uint64_t id = 0) {
  InfoChannelBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

inline const Protocols::InfoChannel *GetInfoChannel(const void *buf) { return flatbuffers::GetRoot<Protocols::InfoChannel>(buf); }

inline bool VerifyInfoChannelBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<Protocols::InfoChannel>(); }

inline void FinishInfoChannelBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<Protocols::InfoChannel> root) { fbb.Finish(root); }

}  // namespace Protocols

#endif  // FLATBUFFERS_GENERATED_INFOCHANNEL_PROTOCOLS_H_
