// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_ANSPING_PROTOCOLS_H_
#define FLATBUFFERS_GENERATED_ANSPING_PROTOCOLS_H_

#include "flatbuffers/flatbuffers.h"

#include "InfoChannel_generated.h"

namespace Protocols {

struct InfoChannel;

}  // namespace Protocols

namespace Protocols {

struct AnsPing;

struct AnsPing FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4,
    VT_CHANNEL = 6
  };
  uint64_t id() const { return GetField<uint64_t>(VT_ID, 0); }
  const Protocols::InfoChannel *channel() const { return GetPointer<const Protocols::InfoChannel *>(VT_CHANNEL); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_CHANNEL) &&
           verifier.VerifyTable(channel()) &&
           verifier.EndTable();
  }
};

struct AnsPingBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) { fbb_.AddElement<uint64_t>(AnsPing::VT_ID, id, 0); }
  void add_channel(flatbuffers::Offset<Protocols::InfoChannel> channel) { fbb_.AddOffset(AnsPing::VT_CHANNEL, channel); }
  AnsPingBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  AnsPingBuilder &operator=(const AnsPingBuilder &);
  flatbuffers::Offset<AnsPing> Finish() {
    auto o = flatbuffers::Offset<AnsPing>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<AnsPing> CreateAnsPing(flatbuffers::FlatBufferBuilder &_fbb,
   uint64_t id = 0,
   flatbuffers::Offset<Protocols::InfoChannel> channel = 0) {
  AnsPingBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_channel(channel);
  return builder_.Finish();
}

inline const Protocols::AnsPing *GetAnsPing(const void *buf) { return flatbuffers::GetRoot<Protocols::AnsPing>(buf); }

inline bool VerifyAnsPingBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<Protocols::AnsPing>(); }

inline void FinishAnsPingBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<Protocols::AnsPing> root) { fbb.Finish(root); }

}  // namespace Protocols

#endif  // FLATBUFFERS_GENERATED_ANSPING_PROTOCOLS_H_
