// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_REQLOGIN_PROTOCOLS_H_
#define FLATBUFFERS_GENERATED_REQLOGIN_PROTOCOLS_H_

#include "flatbuffers/flatbuffers.h"

namespace Protocols {

struct ReqLogin;

struct ReqLogin FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4,
    VT_CHANNEL_ID = 6
  };
  uint64_t id() const { return GetField<uint64_t>(VT_ID, 0); }
  uint64_t channel_id() const { return GetField<uint64_t>(VT_CHANNEL_ID, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID) &&
           VerifyField<uint64_t>(verifier, VT_CHANNEL_ID) &&
           verifier.EndTable();
  }
};

struct ReqLoginBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) { fbb_.AddElement<uint64_t>(ReqLogin::VT_ID, id, 0); }
  void add_channel_id(uint64_t channel_id) { fbb_.AddElement<uint64_t>(ReqLogin::VT_CHANNEL_ID, channel_id, 0); }
  ReqLoginBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  ReqLoginBuilder &operator=(const ReqLoginBuilder &);
  flatbuffers::Offset<ReqLogin> Finish() {
    auto o = flatbuffers::Offset<ReqLogin>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<ReqLogin> CreateReqLogin(flatbuffers::FlatBufferBuilder &_fbb,
   uint64_t id = 0,
   uint64_t channel_id = 0) {
  ReqLoginBuilder builder_(_fbb);
  builder_.add_channel_id(channel_id);
  builder_.add_id(id);
  return builder_.Finish();
}

inline const Protocols::ReqLogin *GetReqLogin(const void *buf) { return flatbuffers::GetRoot<Protocols::ReqLogin>(buf); }

inline bool VerifyReqLoginBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<Protocols::ReqLogin>(); }

inline void FinishReqLoginBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<Protocols::ReqLogin> root) { fbb.Finish(root); }

}  // namespace Protocols

#endif  // FLATBUFFERS_GENERATED_REQLOGIN_PROTOCOLS_H_
