// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_REQPING_PROTOCOLS_H_
#define FLATBUFFERS_GENERATED_REQPING_PROTOCOLS_H_

#include "flatbuffers/flatbuffers.h"

namespace Protocols {

struct ReqPing;

struct ReqPing FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4
  };
  uint64_t id() const { return GetField<uint64_t>(VT_ID, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID) &&
           verifier.EndTable();
  }
};

struct ReqPingBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) { fbb_.AddElement<uint64_t>(ReqPing::VT_ID, id, 0); }
  ReqPingBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  ReqPingBuilder &operator=(const ReqPingBuilder &);
  flatbuffers::Offset<ReqPing> Finish() {
    auto o = flatbuffers::Offset<ReqPing>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<ReqPing> CreateReqPing(flatbuffers::FlatBufferBuilder &_fbb,
   uint64_t id = 0) {
  ReqPingBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

inline const Protocols::ReqPing *GetReqPing(const void *buf) { return flatbuffers::GetRoot<Protocols::ReqPing>(buf); }

inline bool VerifyReqPingBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<Protocols::ReqPing>(); }

inline void FinishReqPingBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<Protocols::ReqPing> root) { fbb.Finish(root); }

}  // namespace Protocols

#endif  // FLATBUFFERS_GENERATED_REQPING_PROTOCOLS_H_
